default: &default  
  pool: 5
  timeout: 5000

  adapter: postgresql
  host: localhost 
  encoding: unicode
  username: miusuario
  password: mipassword

development:  
  <<: *default
  database: proyecto_dev

test:  
  <<: *default
  database: proyecto_test

production:  
  <<: *default
  database: proyecto_prod

